### PR TITLE
Fix server crashes caused by memory leaks in DataManager.

### PR DESCRIPTION
**Pull request by ChimpGamer**
I can provide a crash report which showed me the cause of the error but It's about 8GB and text editors barely can handle it. Anyway, here is the fix.

### CODE REVIEW

**Comment by Esophose** [comment]
The spec of ResultSets say they get automatically closed when their parent Statement gets closed, so I don't think this is necessary? You can see this at the bottom of the description here https://docs.oracle.com/javase/7/docs/api/java/sql/ResultSet.html

**Comment by ChimpGamer** [comment]
Hmm yea if they say so. I barely code in java since I switched to Kotlin so I didn't know. But then I wonder what the cause is since the crash report pointed to the ResultSet.

**Comment by Esophose** [comment]
It should also work the same way in Kotlin, don't see why it wouldn't. I would ask to see the crash report you're referencing but I'd imagine it's more of a heap dump if it's 8gb large, in which case it wouldn't be too helpful to me. I'm currently working on a few optimizations for the plugin's chunk data system which may have a chance of making whatever caused your server to crash less of an issue.

**Comment by ChimpGamer** [comment]
Well it is so big because in the crash report it shows a lot of threads stuff from RoseStacker. More then half of the file is filled with RoseStacker stuff.
image
It's this kind of a crash report.

**Pull request closed without merging**
